const express = require('express');
const router = express.Router();
const controller = require('../controllers/claim.controller');
const { protect, requireModuleAccess, requireActionPermission } = require('../middlewares/auth');
router.use(protect, requireModuleAccess('billing_finance', 'manage'));
router.post('/claims', controller.create);
router.get('/claims', controller.list);
router.get('/claims/:id', controller.get);
router.post('/claims/:id/submit', requireActionPermission('claim_submit'), controller.submit);
router.post('/claims/:id/query-response', controller.queryResponse);
router.post('/claims/:id/settlement', requireActionPermission('settlement'), controller.settlement);
router.get('/sponsor-ledger', controller.ledger);
module.exports = router;
