const express = require('express');
const router = express.Router();
const controller = require('../controllers/ipdTransfer.controller');
const IPDAdmission = require('../models/IPDAdmission');
const IPDBedTransfer = require('../models/IPDBedTransfer');
const { requireResourcePatientAccess } = require('../middlewares/patientAccess');
const { protect, authorize, requireModuleAccess, requireActionPermission } = require('../middlewares/auth');
router.use(protect, requireModuleAccess('ipd', 'view'));
const admissionAccess = requireResourcePatientAccess(IPDAdmission, { idParam: 'id', patientField: 'patientId', hospitalField: 'hospitalId', purpose: 'AUTO', scope: 'clinical_read' });
const transferAccess = requireResourcePatientAccess(IPDBedTransfer, { idParam: 'id', patientField: 'patientId', hospitalField: 'hospitalId', purpose: 'AUTO', scope: 'clinical_read' });
router.get('/admissions/:id/transfers', admissionAccess, controller.listAdmissionTransfers);
router.get('/admissions/:id/accommodation-print-data', admissionAccess, controller.printData);
router.post('/admissions/:id/transfers', requireModuleAccess('ipd', 'manage'), admissionAccess, controller.create);
router.post('/transfers/:id/reserve', requireModuleAccess('ipd', 'manage'), requireActionPermission('transfer_reserve'), transferAccess, controller.reserve);
router.post('/transfers/:id/approve', requireModuleAccess('ipd', 'manage'), requireActionPermission('transfer_approve'), transferAccess, controller.approve);
router.post('/transfers/:id/start', requireModuleAccess('ipd', 'manage'), transferAccess, controller.start);
router.post('/transfers/:id/complete', requireModuleAccess('ipd', 'manage'), requireActionPermission('transfer_complete'), transferAccess, controller.complete);
router.post('/transfers/:id/cancel', requireModuleAccess('ipd', 'manage'), transferAccess, controller.cancel);
router.get('/transfer-board', controller.board);
router.get('/beds/available', controller.availableBeds);
router.post('/beds/:id/cleaning-complete', authorize('admin', 'bed_manager', 'housekeeping', 'staff', 'nurse'), controller.releaseCleaning);
module.exports = router;
