'use strict';

const IPDCharge = require('../models/IPDCharge');
const Invoice = require('../models/Invoice');
const Bill = require('../models/Bill');
const Patient = require('../models/Patient');
const Sale = require('../models/Sale');
const { operationNow } = require('../utils/operationTimeContext');
const { hospitalDateKey } = require('../utils/hospitalDateTime');
const { currentSaleNet, money } = require('./pharmacyReturnClearance.math');

function sessionOption(session) { return session ? { session } : {}; }

async function postReturnAdjustment({ sale, returnRecord, returnValue, createdBy, session }) {
  if (!sale?.admission_id || !sale?.patient_id || Number(returnValue || 0) <= 0) return null;
  const idempotencyKey = `pharmacy-return:${returnRecord._id}:ipd-adjustment`;
  const existing = await IPDCharge.findOne({ hospitalId: sale.hospitalId, idempotencyKey }).session(session || null);
  if (existing) return existing;

  // Separate pharmacy billing is authoritative. This line only keeps the IPD running
  // ledger mathematically aligned before Pharmacy Final Clearance; it is never a
  // second collectible pharmacy invoice.
  const hasOpenMirror = await IPDCharge.exists({
    hospitalId: sale.hospitalId,
    admissionId: sale.admission_id,
    sourceModule: 'Pharmacy',
    sourceId: sale._id,
    isBilled: false,
    status: 'ACTIVE',
    is_active: { $ne: false }
  }).session(session || null);

  const [charge] = await IPDCharge.create([{
    hospitalId: sale.hospitalId,
    admissionId: sale.admission_id,
    patientId: sale.patient_id,
    chargeType: 'Pharmacy',
    adjustmentType: 'WAIVER',
    description: `Medicine return ${returnRecord.returnNumber} - pharmacy credit`,
    quantity: 1,
    rate: 0,
    discountType: 'fixed',
    discountAmount: money(returnValue),
    discountReason: `Medicine return ${returnRecord.returnNumber}`,
    discountApprovedBy: createdBy,
    discountApprovedAt: operationNow(),
    taxMode: 'exempt',
    sourceModule: 'Pharmacy',
    sourceId: sale._id,
    sourceReference: {
      module: 'Pharmacy',
      documentId: sale._id,
      invoiceNumber: sale.invoice_number,
      lineKey: `return:${returnRecord._id}`
    },
    chargeDate: returnRecord.returnedAt || operationNow(),
    chargeDateKey: hospitalDateKey(returnRecord.returnedAt || operationNow()),
    idempotencyKey,
    isAutoGenerated: true,
    isBilled: !hasOpenMirror,
    status: hasOpenMirror ? 'ACTIVE' : 'INVOICED',
    billedAt: hasOpenMirror ? undefined : operationNow(),
    invoiceId: sale.invoice_id,
    billId: sale.bill_id,
    addedBy: createdBy,
    notes: 'Negative pharmacy mirror created from authoritative medicine return; separate pharmacy bill remains source of collection.'
  }], { session });
  return charge;
}

async function syncSaleDocuments({ sale, returnRecord = null, session }) {
  if (sale.invoice_id) {
    const invoice = await Invoice.findById(sale.invoice_id).session(session || null);
    if (invoice) {
      // Pharmacy returns are represented as a credit against the original invoice.
      // Recompute from the authoritative Sale so retries cannot double-credit.
      invoice.credit_note_total = money(Math.max(Number(invoice.credit_note_total || 0), Number(sale.return_amount || 0)));
      invoice.amount_paid = money(sale.amount_paid || 0);
      await invoice.save(sessionOption(session));
    }
  }

  if (sale.bill_id) {
    const bill = await Bill.findById(sale.bill_id).session(session || null);
    if (bill) {
      if (returnRecord && !(bill.items || []).some((row) => String(row?.source_snapshot?.returnId || '') === String(returnRecord._id))) {
        for (const row of returnRecord.items || []) {
          bill.items.push({
            description: `Medicine Return - ${row.medicineName}`,
            amount: -money(row.refundAmount),
            quantity: Number(row.returnedQtyBaseUnits || 1),
            item_type: 'Medicine Return',
            medicine_id: row.medicineId,
            batch_id: row.batchId,
            medicine_name: row.medicineName,
            base_unit: row.baseUnit || 'unit',
            quantity_base_units: Number(row.returnedQtyBaseUnits || 0),
            unit_price: -money(row.ratePerBaseUnit),
            tax_rate: Number(row.taxRate || 0),
            tax_amount: -money(row.taxAmount || 0),
            discount_amount: -money(row.discountReversal || 0),
            taxable_amount: -money(row.taxableAmount || 0),
            source_snapshot: { returnId: returnRecord._id, returnNumber: returnRecord.returnNumber }
          });
        }
      }
      bill.total_amount = money(currentSaleNet(sale));
      bill.paid_amount = money(sale.amount_paid || 0);
      bill.refund_amount = money(sale.refunded_amount || 0);
      await bill.save(sessionOption(session));
    }
  }
}

async function markSaleMirrorsExternallySettled({ sales, settlementId, session }) {
  const at = operationNow();
  for (const sale of sales || []) {
    await IPDCharge.updateMany({
      hospitalId: sale.hospitalId,
      admissionId: sale.admission_id,
      sourceModule: 'Pharmacy',
      sourceId: sale._id,
      isBilled: false,
      status: 'ACTIVE',
      is_active: { $ne: false }
    }, {
      $set: {
        isBilled: true,
        status: 'INVOICED',
        billedAt: at,
        invoiceId: sale.invoice_id || undefined,
        billId: sale.bill_id || undefined,
        notes: `Settled by separate Pharmacy Final Clearance${settlementId ? ` (${settlementId})` : ''}; excluded from IPD invoice collection.`
      }
    }, { session });
    await syncSaleDocuments({ sale, session });
  }
}

async function syncPatientPharmacyOutstanding({ sale, session }) {
  if (!sale?.patient_id || !sale?.hospitalId) return;
  const rows = await Sale.find({
    hospitalId: sale.hospitalId,
    patient_id: sale.patient_id,
    status: { $ne: 'Cancelled' },
    balance_due: { $gt: 0 }
  }).select('balance_due').session(session || null).lean();
  const balance = money(rows.reduce((sum, row) => sum + Number(row.balance_due || 0), 0));
  await Patient.updateOne({ _id: sale.patient_id, hospitalId: sale.hospitalId }, {
    $set: { pharmacy_outstanding_balance: balance, last_pharmacy_transaction: operationNow() }
  }, { session });
}

module.exports = {
  postReturnAdjustment,
  syncSaleDocuments,
  markSaleMirrorsExternallySettled,
  syncPatientPharmacyOutstanding
};
