const mongoose = require('mongoose');

/**
 * IPDCharge is the operational charge source. A charge remains editable only
 * while ACTIVE and unbilled. Once invoiced it is immutable; corrections must
 * be handled through a credit note / authorised adjustment, not deletion.
 */
const ipdChargeSchema = new mongoose.Schema({
  hospitalId: { type: mongoose.Schema.Types.ObjectId, ref: 'Hospital', index: true },
  admissionId: { type: mongoose.Schema.Types.ObjectId, ref: 'IPDAdmission', required: true, index: true },
  patientId: { type: mongoose.Schema.Types.ObjectId, ref: 'Patient', required: true, index: true },
  chargeType: {
    type: String,
    enum: ['Bed', 'Doctor Visit', 'Nursing', 'Procedure', 'Lab Test', 'Pharmacy', 'Surgery', 'Equipment', 'Consultation', 'Emergency', 'Miscellaneous', 'Discount', 'Tax'],
    required: true
  },
  adjustmentType: { type: String, enum: ['CHARGE', 'DISCOUNT', 'TAX', 'WAIVER'], default: 'CHARGE' },
  status: { type: String, enum: ['ACTIVE', 'INVOICED', 'VOIDED', 'CANCELLED'], default: 'ACTIVE', index: true },
  description: { type: String, required: true, trim: true },
  quantity: { type: Number, default: 1, min: 1 },
  rate: { type: Number, default: 0, min: 0 },
  amount: { type: Number, default: 0, min: 0 },
  discount: { type: Number, default: 0, min: 0 },
  netAmount: { type: Number, default: 0 },
  tax: { type: Number, default: 0, min: 0 },
  sourceModule: {
    type: String,
    enum: ['Admission', 'Lab', 'Pharmacy', 'Procedure', 'Manual', 'Bed', 'DoctorRound', 'OT', 'Radiology', 'Billing', 'Discharge'],
    required: true
  },
  sourceId: { type: mongoose.Schema.Types.ObjectId },
  sourceReference: {
    module: { type: String, enum: ['Lab', 'Procedure', 'Radiology', 'Pharmacy', 'Bed', 'DoctorVisit', 'Manual', 'OT', 'IPD', 'Billing', 'Discharge'] },
    documentId: { type: mongoose.Schema.Types.ObjectId },
    invoiceNumber: String,
    billNumber: String,
    // Stable line identifier for legacy bills containing multiple rows that
    // originate from the same prescription or source document.
    lineKey: { type: String, trim: true, index: true }
  },
  chargeDate: { type: Date, default: Date.now },
  chargeDateKey: { type: String, index: true }, // YYYY-MM-DD for idempotent daily bed charging
  idempotencyKey: { type: String, trim: true, sparse: true },
  isAutoGenerated: { type: Boolean, default: false },
  isBilled: { type: Boolean, default: false, index: true },
  billId: { type: mongoose.Schema.Types.ObjectId, ref: 'Bill' },
  invoiceId: { type: mongoose.Schema.Types.ObjectId, ref: 'Invoice' },
  billedAt: Date,
  discountDetails: {
    type: { type: String, enum: ['fixed', 'percentage'], default: 'fixed' },
    reason: String,
    approvedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    approvedAt: Date
  },
  voidedAt: Date,
  voidedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  voidReason: String,
  addedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  notes: { type: String, trim: true }
}, { timestamps: true });

ipdChargeSchema.pre('validate', function calculateCharge(next) {
  this.amount = Number(this.quantity || 0) * Number(this.rate || 0);
  this.netAmount = Number((this.amount - Number(this.discount || 0) + Number(this.tax || 0)).toFixed(2));
  if (!this.chargeDateKey && this.chargeDate) {
    this.chargeDateKey = new Date(this.chargeDate).toISOString().slice(0, 10);
  }
  if (this.adjustmentType === 'DISCOUNT' || this.chargeType === 'Discount') {
    this.rate = 0;
    this.amount = 0;
    this.netAmount = Number((-Math.abs(Number(this.discount || 0))).toFixed(2));
  }
  next();
});

ipdChargeSchema.index({ admissionId: 1, chargeType: 1, status: 1 });
ipdChargeSchema.index({ patientId: 1, chargeDate: -1 });
ipdChargeSchema.index({ sourceModule: 1, sourceId: 1 });
ipdChargeSchema.index({ admissionId: 1, isBilled: 1, status: 1 });
ipdChargeSchema.index({ admissionId: 1, chargeDateKey: 1, chargeType: 1, status: 1 });
ipdChargeSchema.index({ idempotencyKey: 1 }, { unique: true, sparse: true });

module.exports = mongoose.model('IPDCharge', ipdChargeSchema);
