const mongoose = require('mongoose');

const ipdChargeSchema = new mongoose.Schema({
  admissionId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'IPDAdmission',
    required: true,
    index: true
  },
  patientId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Patient',
    required: true
  },
  chargeType: {
    type: String,
    enum: [
      'Bed',
      'Doctor Visit',
      'Nursing',
      'Procedure',
      'Lab Test',
      'Pharmacy',
      'Surgery',
      'Equipment',
      'Consultation',
      'Emergency',
      'Miscellaneous',
      'Discount',
      'Tax'
    ],
    required: true
  },
  description: {
    type: String,
    required: true,
    trim: true
  },
  quantity: {
    type: Number,
    default: 1,
    min: 1
  },
  rate: {
    type: Number,
    default: 0,
    min: 0
  },
  amount: {
    type: Number,
    default: 0,
    min: 0
  },
  discount: {
    type: Number,
    default: 0,
    min: 0
  },
  netAmount: {
    type: Number,
    default: 0
  },
  tax: {
    type: Number,
    default: 0
  },
  sourceModule: {
    type: String,
    enum: ['Admission', 'Lab', 'Pharmacy', 'Procedure', 'Manual', 'Bed', 'DoctorRound'],
    required: true
  },
  sourceId: {
    type: mongoose.Schema.Types.ObjectId
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  isBilled: {
    type: Boolean,
    default: false
  },
  invoiceId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Invoice'
  },
  chargeDate: {
    type: Date,
    default: Date.now
  },
  addedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  notes: {
    type: String,
    trim: true
  }
}, {
  timestamps: true
});

// Calculate net amount before save
ipdChargeSchema.pre('save', function(next) {
  this.amount = this.quantity * this.rate;
  this.netAmount = this.amount - this.discount + this.tax;
  next();
});

// Indexes
ipdChargeSchema.index({ admissionId: 1, chargeType: 1 });
ipdChargeSchema.index({ patientId: 1, chargeDate: -1 });
ipdChargeSchema.index({ sourceModule: 1, sourceId: 1 });

module.exports = mongoose.model('IPDCharge', ipdChargeSchema);